# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainApp(object):
    def setupUi(self, MainApp):
        MainApp.setObjectName("MainApp")
        MainApp.resize(970, 700)
        MainApp.setMinimumSize(QtCore.QSize(900, 700))
        MainApp.setStyleSheet("QObject {\n"
"background-color: blue;\n"
"border: 0px solid;\n"
"margin: 0px;\n"
"padding: 0px;\n"
"border-color: rgb(0, 0, 255);\n"
"}\n"
"QWidget {\n"
"color: black;\n"
"font: 16px \"Segoe UI\";\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"border: 0px solid;\n"
"background:transparent;\n"
"width:8px;\n"
"margin: 0px 0px 0px 0px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"background: rgb(190, 190, 190);\n"
"min-height: 0px;\n"
"border-radius: 4px;\n"
"}\n"
"QScrollBar::sub-line:vertical {\n"
"height: 0 px;\n"
"subcontrol-position: top;\n"
"subcontrol-origin: margin;\n"
"}")
        self.mb_1 = QtWidgets.QWidget(MainApp)
        self.mb_1.setObjectName("mb_1")
        self.mb_voca_adj = QtWidgets.QWidget(self.mb_1)
        self.mb_voca_adj.setGeometry(QtCore.QRect(0, 0, 151, 701))
        self.mb_voca_adj.setStyleSheet("QWidget {\n"
"padding: 0px;\n"
"background-color: rgb(230, 230, 233);\n"
"}\n"
"\n"
"QScrollArea .QLabel {\n"
"color: rgb(170, 170, 170);\n"
"font: 13px;\n"
"margin-left: 10px;\n"
"margin-right: 10px;\n"
"font-weight: bold;\n"
"}\n"
"\n"
"QListWidget::item {\n"
"border-radius: 5px;\n"
"padding: 5px;\n"
"padding-left: 10px;\n"
"padding-right: 10px;\n"
"color: black;\n"
"}\n"
"QListWidget::item:hover {\n"
"background-color: rgb(200, 200, 200);\n"
"}\n"
"\n"
"QListView {\n"
"margin-left: 10px;\n"
"margin-right: 10px;\n"
"}\n"
"QListView::item {\n"
"margin:3px;\n"
"margin-left: 10px;\n"
"font-weight: bold;\n"
"}\n"
"QScrollArea .QWidget  .QWidget .QListWidget {\n"
"font-weight: semi-bold;\n"
"}\n"
"\n"
"QWidget.QPushButton#mb_voca_open {\n"
"margin: 10px 10px 10px 10px;\n"
"font: 16px;\n"
"border-radius: 5px;\n"
"background-color: rgb(0, 155, 255);\n"
"}\n"
"QWidget.QPushButton#mb_voca_open:hover {\n"
"font: 16px;\n"
"color: white;\n"
"border-radius: 5px;\n"
"background-color: rgba(0, 155, 255, 80);\n"
"}")
        self.mb_voca_adj.setObjectName("mb_voca_adj")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.mb_voca_adj)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mb_icon = QtWidgets.QLabel(self.mb_voca_adj)
        self.mb_icon.setMinimumSize(QtCore.QSize(0, 50))
        self.mb_icon.setMaximumSize(QtCore.QSize(16777215, 50))
        self.mb_icon.setText("")
        self.mb_icon.setObjectName("mb_icon")
        self.verticalLayout.addWidget(self.mb_icon)
        self.mb_voca_scroll = QtWidgets.QScrollArea(self.mb_voca_adj)
        self.mb_voca_scroll.setWidgetResizable(True)
        self.mb_voca_scroll.setObjectName("mb_voca_scroll")
        self.mb_voca_scroll_widget = QtWidgets.QWidget()
        self.mb_voca_scroll_widget.setGeometry(QtCore.QRect(0, 0, 151, 581))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mb_voca_scroll_widget.sizePolicy().hasHeightForWidth())
        self.mb_voca_scroll_widget.setSizePolicy(sizePolicy)
        self.mb_voca_scroll_widget.setObjectName("mb_voca_scroll_widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.mb_voca_scroll_widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.mb_voca_widget_1 = QtWidgets.QWidget(self.mb_voca_scroll_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mb_voca_widget_1.sizePolicy().hasHeightForWidth())
        self.mb_voca_widget_1.setSizePolicy(sizePolicy)
        self.mb_voca_widget_1.setObjectName("mb_voca_widget_1")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.mb_voca_widget_1)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.mb_voca_title_1 = QtWidgets.QLabel(self.mb_voca_widget_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mb_voca_title_1.sizePolicy().hasHeightForWidth())
        self.mb_voca_title_1.setSizePolicy(sizePolicy)
        self.mb_voca_title_1.setMinimumSize(QtCore.QSize(0, 20))
        self.mb_voca_title_1.setMaximumSize(QtCore.QSize(16777215, 20))
        self.mb_voca_title_1.setStyleSheet("")
        self.mb_voca_title_1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.mb_voca_title_1.setObjectName("mb_voca_title_1")
        self.verticalLayout_4.addWidget(self.mb_voca_title_1)
        self.mb_voca_word_adj_1 = QtWidgets.QListWidget(self.mb_voca_widget_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mb_voca_word_adj_1.sizePolicy().hasHeightForWidth())
        self.mb_voca_word_adj_1.setSizePolicy(sizePolicy)
        self.mb_voca_word_adj_1.setMaximumSize(QtCore.QSize(16777215, 300))
        self.mb_voca_word_adj_1.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.mb_voca_word_adj_1.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.mb_voca_word_adj_1.setStyleSheet("")
        self.mb_voca_word_adj_1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.mb_voca_word_adj_1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.mb_voca_word_adj_1.setLineWidth(0)
        self.mb_voca_word_adj_1.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.mb_voca_word_adj_1.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.mb_voca_word_adj_1.setAutoScrollMargin(5)
        self.mb_voca_word_adj_1.setProperty("isWrapping", False)
        self.mb_voca_word_adj_1.setResizeMode(QtWidgets.QListView.Adjust)
        self.mb_voca_word_adj_1.setLayoutMode(QtWidgets.QListView.SinglePass)
        self.mb_voca_word_adj_1.setViewMode(QtWidgets.QListView.ListMode)
        self.mb_voca_word_adj_1.setWordWrap(False)
        self.mb_voca_word_adj_1.setObjectName("mb_voca_word_adj_1")
        item = QtWidgets.QListWidgetItem()
        self.mb_voca_word_adj_1.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.mb_voca_word_adj_1.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.mb_voca_word_adj_1.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.mb_voca_word_adj_1.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.mb_voca_word_adj_1.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.mb_voca_word_adj_1.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.mb_voca_word_adj_1.addItem(item)
        self.verticalLayout_4.addWidget(self.mb_voca_word_adj_1)
        self.verticalLayout_3.addWidget(self.mb_voca_widget_1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.mb_voca_scroll.setWidget(self.mb_voca_scroll_widget)
        self.verticalLayout.addWidget(self.mb_voca_scroll)
        self.mb_voca_open = QtWidgets.QPushButton(self.mb_voca_adj)
        self.mb_voca_open.setMinimumSize(QtCore.QSize(0, 60))
        self.mb_voca_open.setMaximumSize(QtCore.QSize(16777215, 60))
        self.mb_voca_open.setObjectName("mb_voca_open")
        self.verticalLayout.addWidget(self.mb_voca_open)
        self.mb_show_adj = QtWidgets.QWidget(self.mb_1)
        self.mb_show_adj.setGeometry(QtCore.QRect(150, 0, 821, 700))
        self.mb_show_adj.setStyleSheet("QWidget {\n"
"background-color: white;\n"
"}\n"
"QPushButton#back, \n"
"QPushButton#forward {\n"
"background-color: rgb(230, 230, 230);\n"
"border-radius: 10px;\n"
"}\n"
"QLabel#mb_show_eng_adj {\n"
"font: 100px;\n"
"font-weight: bold;\n"
"}\n"
"QLabel#mb_show_kor_adj {\n"
"font: 50px;\n"
"font-weight: bold;\n"
"}\n"
"")
        self.mb_show_adj.setObjectName("mb_show_adj")
        self.mb_show_btns_adj = QtWidgets.QWidget(self.mb_show_adj)
        self.mb_show_btns_adj.setGeometry(QtCore.QRect(0, 655, 821, 30))
        self.mb_show_btns_adj.setObjectName("mb_show_btns_adj")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.mb_show_btns_adj)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.mb_show_btn_widget = QtWidgets.QWidget(self.mb_show_btns_adj)
        self.mb_show_btn_widget.setMinimumSize(QtCore.QSize(100, 0))
        self.mb_show_btn_widget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.mb_show_btn_widget.setObjectName("mb_show_btn_widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.mb_show_btn_widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.back = QtWidgets.QPushButton(self.mb_show_btn_widget)
        self.back.setMinimumSize(QtCore.QSize(0, 30))
        self.back.setMaximumSize(QtCore.QSize(30, 16777215))
        self.back.setObjectName("back")
        self.horizontalLayout_2.addWidget(self.back)
        self.dummy = QtWidgets.QLabel(self.mb_show_btn_widget)
        self.dummy.setMaximumSize(QtCore.QSize(50, 16777215))
        self.dummy.setText("")
        self.dummy.setObjectName("dummy")
        self.horizontalLayout_2.addWidget(self.dummy)
        self.forward = QtWidgets.QPushButton(self.mb_show_btn_widget)
        self.forward.setMinimumSize(QtCore.QSize(0, 30))
        self.forward.setMaximumSize(QtCore.QSize(30, 16777215))
        self.forward.setObjectName("forward")
        self.horizontalLayout_2.addWidget(self.forward)
        self.horizontalLayout.addWidget(self.mb_show_btn_widget)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.mb_show_eng_adj = QtWidgets.QLabel(self.mb_show_adj)
        self.mb_show_eng_adj.setGeometry(QtCore.QRect(0, 50, 821, 131))
        self.mb_show_eng_adj.setAlignment(QtCore.Qt.AlignCenter)
        self.mb_show_eng_adj.setObjectName("mb_show_eng_adj")
        self.mb_show_image_adj = QtWidgets.QLabel(self.mb_show_adj)
        self.mb_show_image_adj.setGeometry(QtCore.QRect(0, 190, 821, 361))
        self.mb_show_image_adj.setAlignment(QtCore.Qt.AlignCenter)
        self.mb_show_image_adj.setObjectName("mb_show_image_adj")
        self.mb_show_kor_adj = QtWidgets.QLabel(self.mb_show_adj)
        self.mb_show_kor_adj.setGeometry(QtCore.QRect(0, 560, 821, 81))
        self.mb_show_kor_adj.setAlignment(QtCore.Qt.AlignCenter)
        self.mb_show_kor_adj.setObjectName("mb_show_kor_adj")
        self.mb_show_adj.raise_()
        self.mb_voca_adj.raise_()
        MainApp.setCentralWidget(self.mb_1)

        self.retranslateUi(MainApp)
        QtCore.QMetaObject.connectSlotsByName(MainApp)

    def retranslateUi(self, MainApp):
        _translate = QtCore.QCoreApplication.translate
        MainApp.setWindowTitle(_translate("MainApp", "MainWindow"))
        self.mb_voca_title_1.setText(_translate("MainApp", "Word List"))
        __sortingEnabled = self.mb_voca_word_adj_1.isSortingEnabled()
        self.mb_voca_word_adj_1.setSortingEnabled(False)
        item = self.mb_voca_word_adj_1.item(0)
        item.setText(_translate("MainApp", "jump"))
        item = self.mb_voca_word_adj_1.item(1)
        item.setText(_translate("MainApp", "run"))
        item = self.mb_voca_word_adj_1.item(2)
        item.setText(_translate("MainApp", "walk"))
        item = self.mb_voca_word_adj_1.item(3)
        item.setText(_translate("MainApp", "talk"))
        item = self.mb_voca_word_adj_1.item(4)
        item.setText(_translate("MainApp", "calculate"))
        item = self.mb_voca_word_adj_1.item(5)
        item.setText(_translate("MainApp", "see"))
        item = self.mb_voca_word_adj_1.item(6)
        item.setText(_translate("MainApp", "fly"))
        self.mb_voca_word_adj_1.setSortingEnabled(__sortingEnabled)
        self.mb_voca_open.setText(_translate("MainApp", "New file"))
        self.back.setText(_translate("MainApp", "◀"))
        self.forward.setText(_translate("MainApp", "▶"))
        self.mb_show_eng_adj.setText(_translate("MainApp", "jump"))
        self.mb_show_image_adj.setText(_translate("MainApp", "image"))
        self.mb_show_kor_adj.setText(_translate("MainApp", "점프하다"))
