# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resource/src/ui/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainApp(object):
    def setupUi(self, MainApp):
        MainApp.setObjectName("MainApp")
        MainApp.resize(970, 700)
        MainApp.setMinimumSize(QtCore.QSize(970, 700))
        MainApp.setStyleSheet("QObject {\n"
"border: 0px solid;\n"
"margin: 0px;\n"
"padding: 0px;\n"
"background-color: blue;\n"
"border-color: rgb(0, 0, 255);\n"
"}\n"
"QWidget {\n"
"color: black;\n"
"font: 63 14px \"Noto Sans KR SemiBold\";\n"
"}\n"
"/* scrollbar stylesheet css */\n"
"QScrollBar {\n"
"}\n"
"QScrollBar:vertical {\n"
"border: 0px solid;\n"
"width: 8px;\n"
"margin: 0px;\n"
"}\n"
"QScrollBar::add-page:vertical,\n"
"QScrollBar::sub-page:vertical {\n"
"background: rgba(190, 190, 190, 60);\n"
"border-radius: 4px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"background: rgba(190, 190, 190, 200);\n"
"border-radius: 4px;\n"
"}\n"
"QScrollBar::sub-line:vertical {\n"
"height: 0px;\n"
"subcontrol-position: top;\n"
"subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"height: 0px;\n"
"subcontrol-position: bottom;\n"
"subcontrol-origin: margin;\n"
"}")
        self.mb_1 = QtWidgets.QWidget(MainApp)
        self.mb_1.setObjectName("mb_1")
        self.mb_voca_adj = QtWidgets.QWidget(self.mb_1)
        self.mb_voca_adj.setGeometry(QtCore.QRect(0, 0, 200, 700))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mb_voca_adj.sizePolicy().hasHeightForWidth())
        self.mb_voca_adj.setSizePolicy(sizePolicy)
        self.mb_voca_adj.setMinimumSize(QtCore.QSize(0, 700))
        self.mb_voca_adj.setMaximumSize(QtCore.QSize(200, 16777215))
        self.mb_voca_adj.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.mb_voca_adj.setStyleSheet("/* Pallete --------------------------------- \n"
"\n"
"lightgray : rgb(242, 242, 247)\n"
"gray : rgb(141, 141, 147)\n"
"darkgray : rgb(122, 122, 128)\n"
"\n"
"grayorange : rgb(228, 175, 10)\n"
"pointorange : rgb(250, 188, 1)\n"
"\n"
"blue : rgb(0, 155, 255)\n"
"bluehover : rgba(0, 155, 255, 80)\n"
"\n"
"--------------------------------------- */\n"
"\n"
"QWidget {\n"
"padding: 10px;\n"
"padding: 0px;\n"
"background-color: transparent;\n"
"}\n"
"#mb_voca_adj {\n"
"background-color: rgb(242, 242, 247);\n"
"}\n"
".Line {\n"
"background-color: rgb(227, 227, 233);\n"
"margin: 0px 10px 0px 50px;\n"
"}\n"
"\n"
"\n"
"/* Left - White Grouped Section --------------------------------- */\n"
"#mb_setting_widget,\n"
"#mb_voca_scroll {\n"
"background-color: white;\n"
"border-radius: 10px;\n"
"margin: 0px 10px 10px 10px;\n"
"}\n"
"#mb_setting_widget {\n"
"margin-bottom: 5px;\n"
"}\n"
"#mb_voca_scroll {\n"
"margin-top: 5px;\n"
"}\n"
"#mb_setting_title,\n"
"#mb_voca_total_title {\n"
"margin: 0px 0px 0px 20px;\n"
"color: black;\n"
"font: 14px;\n"
"}\n"
"#mb_voca_setting_button {\n"
"color: rgb(122, 122, 128);\n"
"}\n"
"#mb_voca_setting_button:hover {\n"
"color: rgb(228, 175, 10);\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"/* Left - Setting detail name(ex: Auto Scroll ....) ------------------------------------- */\n"
"#mb_top_bar_play_type_title,\n"
"#mb_top_bar_auto_scroll_title,\n"
"#mb_top_bar_repeat_title {\n"
"font: 12px;\n"
"margin: 0px 0px 0px 30px;\n"
"color: black;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"/* Type PushButton Setting ------------------------------------- */\n"
"#mb_top_bar_play_type .QPushButton {\n"
"font: 11px;\n"
"background-color: rgb(227, 227, 233);\n"
"border-radius: 8px;\n"
"text-align: center;\n"
"color: black;\n"
"}\n"
"#mb_top_bar_play_type .QPushButton:hover {\n"
"background-color: rgba(228, 175, 10, 80);\n"
"}\n"
"#mb_top_bar_play_type .QPushButton:checked {\n"
"color: white;\n"
"background-color: rgb(250, 188, 1);\n"
"}\n"
"#mb_top_bar_only_img {\n"
"margin-right: 10px;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"/* Repeat SpinBox Setting ------------------------------------- */\n"
"#mb_top_bar_repeat_spinbox {\n"
"color: rgb(141, 141, 147);\n"
"selection-background-color: white;\n"
"selection-color: rgb(141, 141, 147);\n"
"}\n"
"#mb_top_bar_repeat_spinbox:hover {\n"
"color: rgb(228, 175, 10);\n"
"selection-color: rgb(228, 175, 10);\n"
"}\n"
"#mb_top_bar_repeat_spinbox:up-arrow:hover,\n"
"#mb_top_bar_repeat_spinbox:down-arrow:hover  {\n"
"color: rgb(228, 175, 10);\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"/* QScrollWidget Label & PushButton part ------------------ */\n"
"QScrollArea {\n"
"margin-bottom: 0px;\n"
"padding-top: 10px;\n"
"}\n"
"QScrollArea .QLabel {\n"
"padding-left: 5px;\n"
"background-position: right;\n"
"}\n"
"/*Lesson1 */\n"
"QScrollArea .QPushButton {\n"
"margin: 5px;\n"
"padding: 0px;\n"
"color: black;\n"
"text-align: left;\n"
"}\n"
"\n"
"/* QListWidget Part ------------------------------ */\n"
"QListView::item {\n"
"border: 0px;\n"
"margin: 5px -8px 5px -4px;\n"
"}\n"
"QListWidget {\n"
"font: 13px;\n"
"font-weight: light;\n"
"padding-right: 4px;\n"
"}\n"
"QListWidget::item {\n"
"padding: 3px;\n"
"padding-left: 30px;\n"
"color: rgb(180, 180, 180);\n"
"}\n"
"QListWidget::item:hover {\n"
"padding-left: 30px;\n"
"margin: 0px -4px 0px -4px;\n"
"color: black;\n"
"background-color: rgb(227, 227, 233);\n"
"}\n"
"QListWidget::item:selected {\n"
"padding-left: 30px;\n"
"margin: 0px -4px 0px -4px;\n"
"background-color: rgb(228, 175, 10);\n"
"color: white;\n"
"}\n"
"QListWidget::indicator {\n"
"border-radius: 8px;\n"
"border: 1px solid;\n"
"border-color: rgb(141, 141, 147);\n"
"background-color: transparent;\n"
"}\n"
"QListWidget::indicator:hover {\n"
"border: 0px solid;\n"
"background-repeat: none;\n"
"background-position: center;\n"
"background-image: url(\"C:/Users/Gonyo/Documents/GitHub/VisualVocaApp/resource/src/img/Indicator.svg\");\n"
"background-color: rgba(250, 188, 1, 120);\n"
"}\n"
"QListWidget::indicator:checked {\n"
"border: 0px solid;\n"
"background-repeat: none;\n"
"background-position: center;\n"
"background-image: url(\"C:/Users/Gonyo/Documents/GitHub/VisualVocaApp/resource/src/img/Indicator.svg\");\n"
"background-color: rgb(250, 188, 1);\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"/* Add Files Part */\n"
"#mb_voca_open {\n"
"margin: 0px 10px 10px 10px;\n"
"color: white;\n"
"font: 16px;\n"
"font-weight: bold;\n"
"border-radius: 5px;\n"
"background-color: rgb(228, 175, 10);\n"
"}\n"
"#mb_voca_open:hover {\n"
"background-color: rgba(228, 175, 10, 80);\n"
"}\n"
"\n"
"\n"
"/* border for temperary */\n"
"#mb_voca_bookmark,\n"
"#mb_voca_refresh {\n"
"border: 1px solid lightgray;\n"
"}")
        self.mb_voca_adj.setObjectName("mb_voca_adj")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.mb_voca_adj)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mb_icon_widget = QtWidgets.QWidget(self.mb_voca_adj)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mb_icon_widget.sizePolicy().hasHeightForWidth())
        self.mb_icon_widget.setSizePolicy(sizePolicy)
        self.mb_icon_widget.setMinimumSize(QtCore.QSize(200, 40))
        self.mb_icon_widget.setMaximumSize(QtCore.QSize(200, 40))
        self.mb_icon_widget.setObjectName("mb_icon_widget")
        self.mb_icon = QtWidgets.QLabel(self.mb_icon_widget)
        self.mb_icon.setGeometry(QtCore.QRect(0, 0, 200, 40))
        self.mb_icon.setMinimumSize(QtCore.QSize(0, 40))
        self.mb_icon.setMaximumSize(QtCore.QSize(16777215, 40))
        self.mb_icon.setLineWidth(0)
        self.mb_icon.setText("")
        self.mb_icon.setIndent(0)
        self.mb_icon.setObjectName("mb_icon")
        self.mb_voca_refresh = QtWidgets.QPushButton(self.mb_icon_widget)
        self.mb_voca_refresh.setGeometry(QtCore.QRect(164, 5, 30, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mb_voca_refresh.sizePolicy().hasHeightForWidth())
        self.mb_voca_refresh.setSizePolicy(sizePolicy)
        self.mb_voca_refresh.setMinimumSize(QtCore.QSize(30, 30))
        self.mb_voca_refresh.setMaximumSize(QtCore.QSize(30, 30))
        self.mb_voca_refresh.setStyleSheet("")
        self.mb_voca_refresh.setText("")
        self.mb_voca_refresh.setObjectName("mb_voca_refresh")
        self.verticalLayout.addWidget(self.mb_icon_widget)
        self.mb_setting_title_bar = QtWidgets.QWidget(self.mb_voca_adj)
        self.mb_setting_title_bar.setMinimumSize(QtCore.QSize(200, 30))
        self.mb_setting_title_bar.setMaximumSize(QtCore.QSize(16777215, 30))
        self.mb_setting_title_bar.setObjectName("mb_setting_title_bar")
        self.mb_setting_title = QtWidgets.QLabel(self.mb_setting_title_bar)
        self.mb_setting_title.setGeometry(QtCore.QRect(0, 0, 160, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mb_setting_title.sizePolicy().hasHeightForWidth())
        self.mb_setting_title.setSizePolicy(sizePolicy)
        self.mb_setting_title.setMinimumSize(QtCore.QSize(160, 30))
        self.mb_setting_title.setMaximumSize(QtCore.QSize(160, 16777215))
        self.mb_setting_title.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.mb_setting_title.setIndent(0)
        self.mb_setting_title.setObjectName("mb_setting_title")
        self.mb_voca_setting_button = QtWidgets.QPushButton(self.mb_setting_title_bar)
        self.mb_voca_setting_button.setGeometry(QtCore.QRect(160, -1, 30, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mb_voca_setting_button.sizePolicy().hasHeightForWidth())
        self.mb_voca_setting_button.setSizePolicy(sizePolicy)
        self.mb_voca_setting_button.setMinimumSize(QtCore.QSize(30, 30))
        self.mb_voca_setting_button.setMaximumSize(QtCore.QSize(30, 30))
        self.mb_voca_setting_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.mb_voca_setting_button.setObjectName("mb_voca_setting_button")
        self.verticalLayout.addWidget(self.mb_setting_title_bar)
        self.mb_setting_widget = QtWidgets.QWidget(self.mb_voca_adj)
        self.mb_setting_widget.setObjectName("mb_setting_widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.mb_setting_widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 10)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.mb_top_bar_play_type = QtWidgets.QWidget(self.mb_setting_widget)
        self.mb_top_bar_play_type.setMinimumSize(QtCore.QSize(0, 37))
        self.mb_top_bar_play_type.setMaximumSize(QtCore.QSize(190, 32))
        self.mb_top_bar_play_type.setObjectName("mb_top_bar_play_type")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.mb_top_bar_play_type)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(4)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.mb_top_bar_play_type_title = QtWidgets.QLabel(self.mb_top_bar_play_type)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mb_top_bar_play_type_title.sizePolicy().hasHeightForWidth())
        self.mb_top_bar_play_type_title.setSizePolicy(sizePolicy)
        self.mb_top_bar_play_type_title.setMaximumSize(QtCore.QSize(70, 16777215))
        self.mb_top_bar_play_type_title.setObjectName("mb_top_bar_play_type_title")
        self.horizontalLayout_7.addWidget(self.mb_top_bar_play_type_title)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.mb_top_bar_all = QtWidgets.QPushButton(self.mb_top_bar_play_type)
        self.mb_top_bar_all.setMinimumSize(QtCore.QSize(26, 22))
        self.mb_top_bar_all.setMaximumSize(QtCore.QSize(26, 22))
        self.mb_top_bar_all.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.mb_top_bar_all.setCheckable(True)
        self.mb_top_bar_all.setChecked(True)
        self.mb_top_bar_all.setObjectName("mb_top_bar_all")
        self.horizontalLayout_7.addWidget(self.mb_top_bar_all)
        self.mb_top_bar_only_eng = QtWidgets.QPushButton(self.mb_top_bar_play_type)
        self.mb_top_bar_only_eng.setMinimumSize(QtCore.QSize(22, 22))
        self.mb_top_bar_only_eng.setMaximumSize(QtCore.QSize(22, 22))
        self.mb_top_bar_only_eng.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.mb_top_bar_only_eng.setCheckable(True)
        self.mb_top_bar_only_eng.setObjectName("mb_top_bar_only_eng")
        self.horizontalLayout_7.addWidget(self.mb_top_bar_only_eng)
        self.mb_top_bar_only_kor = QtWidgets.QPushButton(self.mb_top_bar_play_type)
        self.mb_top_bar_only_kor.setMinimumSize(QtCore.QSize(22, 22))
        self.mb_top_bar_only_kor.setMaximumSize(QtCore.QSize(22, 22))
        self.mb_top_bar_only_kor.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.mb_top_bar_only_kor.setCheckable(True)
        self.mb_top_bar_only_kor.setObjectName("mb_top_bar_only_kor")
        self.horizontalLayout_7.addWidget(self.mb_top_bar_only_kor)
        self.mb_top_bar_only_img = QtWidgets.QPushButton(self.mb_top_bar_play_type)
        self.mb_top_bar_only_img.setMinimumSize(QtCore.QSize(36, 22))
        self.mb_top_bar_only_img.setMaximumSize(QtCore.QSize(36, 22))
        self.mb_top_bar_only_img.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.mb_top_bar_only_img.setCheckable(True)
        self.mb_top_bar_only_img.setObjectName("mb_top_bar_only_img")
        self.horizontalLayout_7.addWidget(self.mb_top_bar_only_img)
        self.verticalLayout_2.addWidget(self.mb_top_bar_play_type)
        self.mb_top_bar_auto_scroll = QtWidgets.QWidget(self.mb_setting_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mb_top_bar_auto_scroll.sizePolicy().hasHeightForWidth())
        self.mb_top_bar_auto_scroll.setSizePolicy(sizePolicy)
        self.mb_top_bar_auto_scroll.setMinimumSize(QtCore.QSize(190, 0))
        self.mb_top_bar_auto_scroll.setMaximumSize(QtCore.QSize(190, 30))
        self.mb_top_bar_auto_scroll.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.mb_top_bar_auto_scroll.setObjectName("mb_top_bar_auto_scroll")
        self.mb_top_bar_auto_scroll_verticalLayout = QtWidgets.QHBoxLayout(self.mb_top_bar_auto_scroll)
        self.mb_top_bar_auto_scroll_verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.mb_top_bar_auto_scroll_verticalLayout.setSpacing(5)
        self.mb_top_bar_auto_scroll_verticalLayout.setObjectName("mb_top_bar_auto_scroll_verticalLayout")
        self.mb_top_bar_auto_scroll_title = QtWidgets.QLabel(self.mb_top_bar_auto_scroll)
        self.mb_top_bar_auto_scroll_title.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mb_top_bar_auto_scroll_title.sizePolicy().hasHeightForWidth())
        self.mb_top_bar_auto_scroll_title.setSizePolicy(sizePolicy)
        self.mb_top_bar_auto_scroll_title.setMinimumSize(QtCore.QSize(100, 30))
        self.mb_top_bar_auto_scroll_title.setMaximumSize(QtCore.QSize(100, 16777215))
        self.mb_top_bar_auto_scroll_title.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.mb_top_bar_auto_scroll_title.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.mb_top_bar_auto_scroll_title.setObjectName("mb_top_bar_auto_scroll_title")
        self.mb_top_bar_auto_scroll_verticalLayout.addWidget(self.mb_top_bar_auto_scroll_title)
        spacerItem1 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.mb_top_bar_auto_scroll_verticalLayout.addItem(spacerItem1)
        self.verticalLayout_2.addWidget(self.mb_top_bar_auto_scroll)
        self.mb_top_bar_repeat = QtWidgets.QWidget(self.mb_setting_widget)
        self.mb_top_bar_repeat.setMinimumSize(QtCore.QSize(190, 30))
        self.mb_top_bar_repeat.setMaximumSize(QtCore.QSize(190, 30))
        self.mb_top_bar_repeat.setObjectName("mb_top_bar_repeat")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.mb_top_bar_repeat)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.mb_top_bar_repeat_title = QtWidgets.QLabel(self.mb_top_bar_repeat)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mb_top_bar_repeat_title.sizePolicy().hasHeightForWidth())
        self.mb_top_bar_repeat_title.setSizePolicy(sizePolicy)
        self.mb_top_bar_repeat_title.setMinimumSize(QtCore.QSize(100, 30))
        self.mb_top_bar_repeat_title.setObjectName("mb_top_bar_repeat_title")
        self.horizontalLayout_6.addWidget(self.mb_top_bar_repeat_title)
        self.mb_top_bar_repeat_spinbox = QtWidgets.QSpinBox(self.mb_top_bar_repeat)
        self.mb_top_bar_repeat_spinbox.setMinimumSize(QtCore.QSize(53, 0))
        self.mb_top_bar_repeat_spinbox.setMaximumSize(QtCore.QSize(53, 16777215))
        self.mb_top_bar_repeat_spinbox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.mb_top_bar_repeat_spinbox.setAlignment(QtCore.Qt.AlignCenter)
        self.mb_top_bar_repeat_spinbox.setPrefix("")
        self.mb_top_bar_repeat_spinbox.setMinimum(1)
        self.mb_top_bar_repeat_spinbox.setMaximum(10)
        self.mb_top_bar_repeat_spinbox.setObjectName("mb_top_bar_repeat_spinbox")
        self.horizontalLayout_6.addWidget(self.mb_top_bar_repeat_spinbox)
        self.verticalLayout_2.addWidget(self.mb_top_bar_repeat)
        self.verticalLayout.addWidget(self.mb_setting_widget)
        self.mb_voca_title_bar = QtWidgets.QWidget(self.mb_voca_adj)
        self.mb_voca_title_bar.setMinimumSize(QtCore.QSize(0, 40))
        self.mb_voca_title_bar.setMaximumSize(QtCore.QSize(16777215, 40))
        self.mb_voca_title_bar.setObjectName("mb_voca_title_bar")
        self.mb_voca_total_title = QtWidgets.QLabel(self.mb_voca_title_bar)
        self.mb_voca_total_title.setGeometry(QtCore.QRect(0, 10, 160, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mb_voca_total_title.sizePolicy().hasHeightForWidth())
        self.mb_voca_total_title.setSizePolicy(sizePolicy)
        self.mb_voca_total_title.setMinimumSize(QtCore.QSize(160, 30))
        self.mb_voca_total_title.setMaximumSize(QtCore.QSize(160, 16777215))
        self.mb_voca_total_title.setLineWidth(0)
        self.mb_voca_total_title.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.mb_voca_total_title.setIndent(0)
        self.mb_voca_total_title.setObjectName("mb_voca_total_title")
        self.mb_voca_bookmark = QtWidgets.QPushButton(self.mb_voca_title_bar)
        self.mb_voca_bookmark.setGeometry(QtCore.QRect(160, 10, 30, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mb_voca_bookmark.sizePolicy().hasHeightForWidth())
        self.mb_voca_bookmark.setSizePolicy(sizePolicy)
        self.mb_voca_bookmark.setMinimumSize(QtCore.QSize(30, 30))
        self.mb_voca_bookmark.setMaximumSize(QtCore.QSize(30, 30))
        self.mb_voca_bookmark.setStyleSheet("")
        self.mb_voca_bookmark.setText("")
        self.mb_voca_bookmark.setCheckable(True)
        self.mb_voca_bookmark.setObjectName("mb_voca_bookmark")
        self.verticalLayout.addWidget(self.mb_voca_title_bar)
        self.mb_voca_scroll = QtWidgets.QScrollArea(self.mb_voca_adj)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mb_voca_scroll.sizePolicy().hasHeightForWidth())
        self.mb_voca_scroll.setSizePolicy(sizePolicy)
        self.mb_voca_scroll.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.mb_voca_scroll.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.mb_voca_scroll.setWidgetResizable(True)
        self.mb_voca_scroll.setObjectName("mb_voca_scroll")
        self.mb_voca_scroll_widget = QtWidgets.QWidget()
        self.mb_voca_scroll_widget.setGeometry(QtCore.QRect(0, 0, 180, 408))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mb_voca_scroll_widget.sizePolicy().hasHeightForWidth())
        self.mb_voca_scroll_widget.setSizePolicy(sizePolicy)
        self.mb_voca_scroll_widget.setObjectName("mb_voca_scroll_widget")
        self.mb_voca_scroll_widget_verticalLayout = QtWidgets.QVBoxLayout(self.mb_voca_scroll_widget)
        self.mb_voca_scroll_widget_verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.mb_voca_scroll_widget_verticalLayout.setSpacing(0)
        self.mb_voca_scroll_widget_verticalLayout.setObjectName("mb_voca_scroll_widget_verticalLayout")
        self.mb_voca_widget_0 = QtWidgets.QWidget(self.mb_voca_scroll_widget)
        self.mb_voca_widget_0.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mb_voca_widget_0.sizePolicy().hasHeightForWidth())
        self.mb_voca_widget_0.setSizePolicy(sizePolicy)
        self.mb_voca_widget_0.setMinimumSize(QtCore.QSize(180, 30))
        self.mb_voca_widget_0.setObjectName("mb_voca_widget_0")
        self.mb_voca_widget_verticalLayout = QtWidgets.QVBoxLayout(self.mb_voca_widget_0)
        self.mb_voca_widget_verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.mb_voca_widget_verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.mb_voca_widget_verticalLayout.setSpacing(0)
        self.mb_voca_widget_verticalLayout.setObjectName("mb_voca_widget_verticalLayout")
        self.mb_voca_button_adj_0 = QtWidgets.QWidget(self.mb_voca_widget_0)
        self.mb_voca_button_adj_0.setMinimumSize(QtCore.QSize(180, 35))
        self.mb_voca_button_adj_0.setMaximumSize(QtCore.QSize(180, 30))
        self.mb_voca_button_adj_0.setStyleSheet("QWidget:hover {\n"
"background-color: rgb(242, 214, 130);\n"
"}")
        self.mb_voca_button_adj_0.setObjectName("mb_voca_button_adj_0")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.mb_voca_button_adj_0)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.mb_voca_button_icon_adj_0 = QtWidgets.QLabel(self.mb_voca_button_adj_0)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mb_voca_button_icon_adj_0.sizePolicy().hasHeightForWidth())
        self.mb_voca_button_icon_adj_0.setSizePolicy(sizePolicy)
        self.mb_voca_button_icon_adj_0.setMinimumSize(QtCore.QSize(30, 25))
        self.mb_voca_button_icon_adj_0.setMaximumSize(QtCore.QSize(16777215, 25))
        self.mb_voca_button_icon_adj_0.setText("")
        self.mb_voca_button_icon_adj_0.setObjectName("mb_voca_button_icon_adj_0")
        self.horizontalLayout_5.addWidget(self.mb_voca_button_icon_adj_0)
        self.mb_voca_button_group_title_adj_0 = QtWidgets.QPushButton(self.mb_voca_button_adj_0)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mb_voca_button_group_title_adj_0.sizePolicy().hasHeightForWidth())
        self.mb_voca_button_group_title_adj_0.setSizePolicy(sizePolicy)
        self.mb_voca_button_group_title_adj_0.setMinimumSize(QtCore.QSize(0, 35))
        self.mb_voca_button_group_title_adj_0.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.mb_voca_button_group_title_adj_0.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.mb_voca_button_group_title_adj_0.setFocusPolicy(QtCore.Qt.NoFocus)
        self.mb_voca_button_group_title_adj_0.setCheckable(True)
        self.mb_voca_button_group_title_adj_0.setChecked(False)
        self.mb_voca_button_group_title_adj_0.setObjectName("mb_voca_button_group_title_adj_0")
        self.horizontalLayout_5.addWidget(self.mb_voca_button_group_title_adj_0)
        self.mb_voca_widget_verticalLayout.addWidget(self.mb_voca_button_adj_0)
        self.mb_voca_word_adj_0 = QtWidgets.QListWidget(self.mb_voca_widget_0)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mb_voca_word_adj_0.sizePolicy().hasHeightForWidth())
        self.mb_voca_word_adj_0.setSizePolicy(sizePolicy)
        self.mb_voca_word_adj_0.setMinimumSize(QtCore.QSize(184, 0))
        self.mb_voca_word_adj_0.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.mb_voca_word_adj_0.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.mb_voca_word_adj_0.setFocusPolicy(QtCore.Qt.NoFocus)
        self.mb_voca_word_adj_0.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.mb_voca_word_adj_0.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.mb_voca_word_adj_0.setFrameShadow(QtWidgets.QFrame.Plain)
        self.mb_voca_word_adj_0.setLineWidth(0)
        self.mb_voca_word_adj_0.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.mb_voca_word_adj_0.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.mb_voca_word_adj_0.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.mb_voca_word_adj_0.setAutoScrollMargin(1)
        self.mb_voca_word_adj_0.setProperty("showDropIndicator", True)
        self.mb_voca_word_adj_0.setAlternatingRowColors(False)
        self.mb_voca_word_adj_0.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.mb_voca_word_adj_0.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.mb_voca_word_adj_0.setMovement(QtWidgets.QListView.Free)
        self.mb_voca_word_adj_0.setProperty("isWrapping", False)
        self.mb_voca_word_adj_0.setResizeMode(QtWidgets.QListView.Adjust)
        self.mb_voca_word_adj_0.setLayoutMode(QtWidgets.QListView.SinglePass)
        self.mb_voca_word_adj_0.setViewMode(QtWidgets.QListView.ListMode)
        self.mb_voca_word_adj_0.setWordWrap(False)
        self.mb_voca_word_adj_0.setObjectName("mb_voca_word_adj_0")
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item.setCheckState(QtCore.Qt.Checked)
        self.mb_voca_word_adj_0.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.mb_voca_word_adj_0.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.mb_voca_word_adj_0.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.mb_voca_word_adj_0.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.mb_voca_word_adj_0.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.mb_voca_word_adj_0.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.mb_voca_word_adj_0.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.mb_voca_word_adj_0.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.mb_voca_word_adj_0.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.mb_voca_word_adj_0.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.mb_voca_word_adj_0.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.mb_voca_word_adj_0.addItem(item)
        self.mb_voca_widget_verticalLayout.addWidget(self.mb_voca_word_adj_0)
        self.mb_voca_scroll_widget_verticalLayout.addWidget(self.mb_voca_widget_0)
        self.mb_voca_scroll.setWidget(self.mb_voca_scroll_widget)
        self.verticalLayout.addWidget(self.mb_voca_scroll)
        self.mb_voca_open = QtWidgets.QPushButton(self.mb_voca_adj)
        self.mb_voca_open.setMinimumSize(QtCore.QSize(0, 50))
        self.mb_voca_open.setMaximumSize(QtCore.QSize(16777215, 50))
        self.mb_voca_open.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.mb_voca_open.setObjectName("mb_voca_open")
        self.verticalLayout.addWidget(self.mb_voca_open)
        self.mb_show_adj = QtWidgets.QWidget(self.mb_1)
        self.mb_show_adj.setGeometry(QtCore.QRect(200, 0, 771, 700))
        self.mb_show_adj.setStyleSheet("#mb_show_adj {\n"
"background-color: white;\n"
"}\n"
"QWidget {\n"
"padding: 0px;\n"
"margin: 0px;\n"
"background-color: transparent;\n"
"}\n"
"\n"
"/* Top/Bottom button PushButton Part*/\n"
"#mb_show_btns_adj .QPushButton {\n"
"font: 11px;\n"
"padding: 0px;\n"
"background-color: white;\n"
"border-radius: 8px;\n"
"text-align: center;\n"
"color: black;\n"
"}\n"
"#mb_show_btns_adj .QPushButton:hover {\n"
"color: white;\n"
"background-color: rgb(228, 175, 10);\n"
"}\n"
"\n"
"\n"
"/* Bottom Button Part */\n"
"#mb_show_btns_adj,\n"
"#mb_show_btns_adj .QWidget,\n"
"#mb_show_btns_adj .QWidget .QLabel {\n"
"background-color: transparent;\n"
"}\n"
"\n"
"/* Main Show Word Part*/\n"
"#mb_show_eng_adj {\n"
"font: 100px;\n"
"color: black;\n"
"font-weight: bold;\n"
"}\n"
"#mb_show_kor_adj {\n"
"color: black;\n"
"font: 50px;\n"
"font-weight: bold;\n"
"}\n"
"#mb_show_image_adj {\n"
"color: black;\n"
"font: 20px;\n"
"}\n"
"#mb_show_special_case_adj {\n"
"background-repeat: none;\n"
"background-position: center;\n"
"background-color: transparent;\n"
"background-image: \'\';\n"
"font: 100px;\n"
"font-weight: bold;\n"
"color: transparent;\n"
"}\n"
"#mb_show_dev_contact {\n"
"color: black;\n"
"font: 10px;\n"
"}\n"
"#mb_show_dev_detail {\n"
"font: 10px;\n"
"color: rgb(112, 112, 112);\n"
"}")
        self.mb_show_adj.setObjectName("mb_show_adj")
        self.mb_show_btns_adj = QtWidgets.QWidget(self.mb_show_adj)
        self.mb_show_btns_adj.setGeometry(QtCore.QRect(0, 654, 771, 30))
        self.mb_show_btns_adj.setObjectName("mb_show_btns_adj")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.mb_show_btns_adj)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.mb_show_btn_widget = QtWidgets.QWidget(self.mb_show_btns_adj)
        self.mb_show_btn_widget.setMinimumSize(QtCore.QSize(0, 0))
        self.mb_show_btn_widget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.mb_show_btn_widget.setObjectName("mb_show_btn_widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.mb_show_btn_widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.back = QtWidgets.QPushButton(self.mb_show_btn_widget)
        self.back.setMinimumSize(QtCore.QSize(26, 26))
        self.back.setMaximumSize(QtCore.QSize(26, 26))
        self.back.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.back.setObjectName("back")
        self.horizontalLayout_2.addWidget(self.back)
        self.dummy = QtWidgets.QLabel(self.mb_show_btn_widget)
        self.dummy.setMinimumSize(QtCore.QSize(26, 26))
        self.dummy.setMaximumSize(QtCore.QSize(26, 26))
        self.dummy.setText("")
        self.dummy.setObjectName("dummy")
        self.horizontalLayout_2.addWidget(self.dummy)
        self.pause = QtWidgets.QPushButton(self.mb_show_btn_widget)
        self.pause.setMinimumSize(QtCore.QSize(26, 26))
        self.pause.setMaximumSize(QtCore.QSize(26, 26))
        self.pause.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pause.setObjectName("pause")
        self.horizontalLayout_2.addWidget(self.pause)
        self.dummy_2 = QtWidgets.QLabel(self.mb_show_btn_widget)
        self.dummy_2.setMinimumSize(QtCore.QSize(26, 26))
        self.dummy_2.setMaximumSize(QtCore.QSize(26, 26))
        self.dummy_2.setText("")
        self.dummy_2.setObjectName("dummy_2")
        self.horizontalLayout_2.addWidget(self.dummy_2)
        self.forward = QtWidgets.QPushButton(self.mb_show_btn_widget)
        self.forward.setMinimumSize(QtCore.QSize(26, 26))
        self.forward.setMaximumSize(QtCore.QSize(26, 26))
        self.forward.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.forward.setObjectName("forward")
        self.horizontalLayout_2.addWidget(self.forward)
        self.horizontalLayout.addWidget(self.mb_show_btn_widget)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.mb_show_eng_adj = QtWidgets.QLabel(self.mb_show_adj)
        self.mb_show_eng_adj.setGeometry(QtCore.QRect(0, 10, 771, 140))
        self.mb_show_eng_adj.setText("")
        self.mb_show_eng_adj.setAlignment(QtCore.Qt.AlignCenter)
        self.mb_show_eng_adj.setObjectName("mb_show_eng_adj")
        self.mb_show_image_adj = QtWidgets.QLabel(self.mb_show_adj)
        self.mb_show_image_adj.setGeometry(QtCore.QRect(0, 160, 771, 381))
        self.mb_show_image_adj.setText("")
        self.mb_show_image_adj.setAlignment(QtCore.Qt.AlignCenter)
        self.mb_show_image_adj.setObjectName("mb_show_image_adj")
        self.mb_show_kor_adj = QtWidgets.QLabel(self.mb_show_adj)
        self.mb_show_kor_adj.setGeometry(QtCore.QRect(0, 540, 771, 81))
        self.mb_show_kor_adj.setText("")
        self.mb_show_kor_adj.setAlignment(QtCore.Qt.AlignCenter)
        self.mb_show_kor_adj.setObjectName("mb_show_kor_adj")
        self.mb_show_special_case_adj = QtWidgets.QLabel(self.mb_show_adj)
        self.mb_show_special_case_adj.setGeometry(QtCore.QRect(0, 0, 771, 700))
        self.mb_show_special_case_adj.setAlignment(QtCore.Qt.AlignCenter)
        self.mb_show_special_case_adj.setWordWrap(True)
        self.mb_show_special_case_adj.setObjectName("mb_show_special_case_adj")
        self.mb_show_dev = QtWidgets.QWidget(self.mb_show_adj)
        self.mb_show_dev.setGeometry(QtCore.QRect(0, 620, 770, 67))
        self.mb_show_dev.setObjectName("mb_show_dev")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.mb_show_dev)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.mb_show_dev_contact = QtWidgets.QLabel(self.mb_show_dev)
        self.mb_show_dev_contact.setMinimumSize(QtCore.QSize(80, 100))
        self.mb_show_dev_contact.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.mb_show_dev_contact.setObjectName("mb_show_dev_contact")
        self.horizontalLayout_3.addWidget(self.mb_show_dev_contact)
        self.mb_show_dev_detail = QtWidgets.QLabel(self.mb_show_dev)
        self.mb_show_dev_detail.setMinimumSize(QtCore.QSize(250, 100))
        self.mb_show_dev_detail.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.mb_show_dev_detail.setObjectName("mb_show_dev_detail")
        self.horizontalLayout_3.addWidget(self.mb_show_dev_detail)
        self.mb_show_ignore_button = QtWidgets.QPushButton(self.mb_show_adj)
        self.mb_show_ignore_button.setGeometry(QtCore.QRect(732, 0, 31, 28))
        self.mb_show_ignore_button.setText("")
        self.mb_show_ignore_button.setObjectName("mb_show_ignore_button")
        self.mb_show_special_case_adj.raise_()
        self.mb_show_eng_adj.raise_()
        self.mb_show_image_adj.raise_()
        self.mb_show_kor_adj.raise_()
        self.mb_show_btns_adj.raise_()
        self.mb_show_dev.raise_()
        self.mb_show_ignore_button.raise_()
        self.mb_show_adj.raise_()
        self.mb_voca_adj.raise_()
        MainApp.setCentralWidget(self.mb_1)

        self.retranslateUi(MainApp)
        self.mb_voca_word_adj_0.setCurrentRow(-1)
        QtCore.QMetaObject.connectSlotsByName(MainApp)
        MainApp.setTabOrder(self.mb_voca_refresh, self.mb_voca_setting_button)
        MainApp.setTabOrder(self.mb_voca_setting_button, self.mb_top_bar_all)
        MainApp.setTabOrder(self.mb_top_bar_all, self.mb_top_bar_only_eng)
        MainApp.setTabOrder(self.mb_top_bar_only_eng, self.mb_top_bar_only_kor)
        MainApp.setTabOrder(self.mb_top_bar_only_kor, self.mb_top_bar_only_img)
        MainApp.setTabOrder(self.mb_top_bar_only_img, self.mb_top_bar_repeat_spinbox)
        MainApp.setTabOrder(self.mb_top_bar_repeat_spinbox, self.mb_voca_bookmark)
        MainApp.setTabOrder(self.mb_voca_bookmark, self.mb_voca_scroll)
        MainApp.setTabOrder(self.mb_voca_scroll, self.mb_voca_open)
        MainApp.setTabOrder(self.mb_voca_open, self.back)
        MainApp.setTabOrder(self.back, self.pause)
        MainApp.setTabOrder(self.pause, self.forward)

    def retranslateUi(self, MainApp):
        _translate = QtCore.QCoreApplication.translate
        MainApp.setWindowTitle(_translate("MainApp", "MainWindow"))
        self.mb_setting_title.setText(_translate("MainApp", "Setting"))
        self.mb_voca_setting_button.setText(_translate("MainApp", "≡"))
        self.mb_top_bar_play_type_title.setText(_translate("MainApp", "Type"))
        self.mb_top_bar_all.setText(_translate("MainApp", "All"))
        self.mb_top_bar_only_eng.setText(_translate("MainApp", "En"))
        self.mb_top_bar_only_kor.setText(_translate("MainApp", "Ko"))
        self.mb_top_bar_only_img.setText(_translate("MainApp", "Img"))
        self.mb_top_bar_auto_scroll_title.setText(_translate("MainApp", "Auto Scroll"))
        self.mb_top_bar_repeat_title.setText(_translate("MainApp", "Repeat"))
        self.mb_top_bar_repeat_spinbox.setSuffix(_translate("MainApp", " 번"))
        self.mb_voca_total_title.setText(_translate("MainApp", "Word List"))
        self.mb_voca_button_group_title_adj_0.setText(_translate("MainApp", "Lesson 1"))
        self.mb_voca_word_adj_0.setStyleSheet(_translate("MainApp", "/* Pallete --------------------------------- \n"
"\n"
"lightgray : rgb(242, 242, 247)\n"
"gray : rgb(141, 141, 147)\n"
"darkgray : rgb(122, 122, 128)\n"
"\n"
"grayorange : rgb(228, 175, 10)\n"
"pointorange : rgb(250, 188, 1)\n"
"\n"
"blue : rgb(0, 155, 255)\n"
"bluehover : rgba(0, 155, 255, 80)\n"
"\n"
"--------------------------------------- */\n"
"\n"
"QWidget {\n"
"padding: 10px;\n"
"padding: 0px;\n"
"background-color: transparent;\n"
"}\n"
"#mb_voca_adj {\n"
"background-color: rgb(242, 242, 247);\n"
"}\n"
".Line {\n"
"background-color: rgb(227, 227, 233);\n"
"margin: 0px 10px 0px 50px;\n"
"}\n"
"\n"
"\n"
"/* Left - White Grouped Section --------------------------------- */\n"
"#mb_setting_widget,\n"
"#mb_voca_scroll {\n"
"background-color: white;\n"
"border-radius: 10px;\n"
"margin: 0px 10px 10px 10px;\n"
"}\n"
"#mb_setting_widget {\n"
"margin-bottom: 5px;\n"
"}\n"
"#mb_voca_scroll {\n"
"margin-top: 5px;\n"
"}\n"
"#mb_setting_title,\n"
"#mb_voca_total_title {\n"
"margin: 0px 0px 0px 20px;\n"
"color: black;\n"
"font: 14px;\n"
"}\n"
"#mb_voca_setting_button {\n"
"color: rgb(122, 122, 128);\n"
"}\n"
"#mb_voca_setting_button:hover {\n"
"color: rgb(228, 175, 10);\n"
"}\n"
"/* Left - Setting detail name(ex: Auto Scroll ....) ------------------------------------- */\n"
"#mb_top_bar_play_type_title,\n"
"#mb_top_bar_auto_scroll_title,\n"
"#mb_top_bar_repeat_title {\n"
"font: 12px;\n"
"margin: 0px 0px 0px 30px;\n"
"color: black;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"/* Type PushButton Setting ------------------------------------- */\n"
"#mb_top_bar_play_type .QPushButton {\n"
"font: 11px;\n"
"background-color: rgb(227, 227, 233);\n"
"border-radius: 8px;\n"
"text-align: center;\n"
"color: black;\n"
"}\n"
"#mb_top_bar_play_type .QPushButton:hover {\n"
"background-color: rgba(228, 175, 10, 80);\n"
"}\n"
"#mb_top_bar_play_type .QPushButton:checked {\n"
"color: white;\n"
"background-color: rgb(250, 188, 1);\n"
"}\n"
"#mb_top_bar_only_img {\n"
"margin-right: 10px;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"/* Repeat SpinBox Setting ------------------------------------- */\n"
"#mb_top_bar_repeat_spinbox {\n"
"color: rgb(141, 141, 147);\n"
"}\n"
"#mb_top_bar_repeat_spinbox:hover {\n"
"color: rgb(228, 175, 10);\n"
"}\n"
"#mb_top_bar_repeat_spinbox:up-arrow:hover,\n"
"#mb_top_bar_repeat_spinbox:down-arrow:hover  {\n"
"color: rgb(228, 175, 10);\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"/* QScrollWidget Label & PushButton part ------------------ */\n"
"QScrollArea {\n"
"margin-bottom: 0px;\n"
"padding-top: 10px;\n"
"}\n"
"/*Lesson1 */\n"
"QScrollArea .QLabel {\n"
"padding-left: 5px;\n"
"}\n"
"QScrollArea .QPushButton {\n"
"margin: 5px 10px 5px 10px;\n"
"padding: 0px;\n"
"color: black;\n"
"text-align: left;\n"
"}\n"
"\n"
"/* QListWidget Part ------------------------------ */\n"
"QListView::item {\n"
"border: 0px;\n"
"margin: 5px -8px 5px -4px;\n"
"}\n"
"QListWidget {\n"
"font: 13px;\n"
"font-weight: light;\n"
"padding-right: 4px;\n"
"}\n"
"QListWidget::item {\n"
"padding: 3px;\n"
"padding-left: 30px;\n"
"color: rgb(180, 180, 180);\n"
"}\n"
"QListWidget::item:hover {\n"
"padding-left: 30px;\n"
"margin: 0px -4px 0px -4px;\n"
"color: black;\n"
"background-color: rgb(227, 227, 233);\n"
"}\n"
"QListWidget::item:selected {\n"
"padding-left: 30px;\n"
"margin: 0px -4px 0px -4px;\n"
"background-color: rgb(228, 175, 10);\n"
"color: white;\n"
"}\n"
"QListWidget::indicator {\n"
"border-radius: 6px;\n"
"border: 1px solid;\n"
"border-color: rgb(141, 141, 147);\n"
"background-color: transparent;\n"
"}\n"
"QListWidget::indicator:hover {\n"
"border: 0px solid;\n"
"background-repeat: none;\n"
"background-position: center;\n"
"background-image: url(\"C:/Users/Gonyo/Documents/GitHub/VisualVocaApp/resource/src/img/Indicator.svg\");\n"
"background-color: rgba(250, 188, 1, 120);\n"
"}\n"
"QListWidget::indicator:checked {\n"
"border: 0px solid;\n"
"background-repeat: none;\n"
"background-position: center;\n"
"background-image: url(\"C:/Users/Gonyo/Documents/GitHub/VisualVocaApp/resource/src/img/Indicator.svg\");\n"
"background-color: rgb(250, 188, 1);\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"/* Add Files Part */\n"
"#mb_voca_open {\n"
"margin: 0px 10px 10px 10px;\n"
"color: white;\n"
"font: 16px;\n"
"font-weight: bold;\n"
"border-radius: 5px;\n"
"background-color: rgb(228, 175, 10);\n"
"}\n"
"#mb_voca_open:hover {\n"
"background-color: rgba(228, 175, 10, 80);\n"
"}\n"
"\n"
"\n"
"/* border for temperary */\n"
"#mb_voca_bookmark,\n"
"#mb_voca_refresh {\n"
"border: 1px solid blue;\n"
"}"))
        self.mb_voca_word_adj_0.setSortingEnabled(False)
        __sortingEnabled = self.mb_voca_word_adj_0.isSortingEnabled()
        self.mb_voca_word_adj_0.setSortingEnabled(False)
        item = self.mb_voca_word_adj_0.item(0)
        item.setText(_translate("MainApp", "jump"))
        item = self.mb_voca_word_adj_0.item(1)
        item.setText(_translate("MainApp", "run"))
        item = self.mb_voca_word_adj_0.item(2)
        item.setText(_translate("MainApp", "done"))
        item = self.mb_voca_word_adj_0.item(3)
        item.setText(_translate("MainApp", "github"))
        item = self.mb_voca_word_adj_0.item(4)
        item.setText(_translate("MainApp", "commit"))
        item = self.mb_voca_word_adj_0.item(5)
        item.setText(_translate("MainApp", "test"))
        item = self.mb_voca_word_adj_0.item(6)
        item.setText(_translate("MainApp", "python"))
        item = self.mb_voca_word_adj_0.item(7)
        item.setText(_translate("MainApp", "walk"))
        item = self.mb_voca_word_adj_0.item(8)
        item.setText(_translate("MainApp", "talk"))
        item = self.mb_voca_word_adj_0.item(9)
        item.setText(_translate("MainApp", "calculate"))
        item = self.mb_voca_word_adj_0.item(10)
        item.setText(_translate("MainApp", "see"))
        item = self.mb_voca_word_adj_0.item(11)
        item.setText(_translate("MainApp", "fly"))
        self.mb_voca_word_adj_0.setSortingEnabled(__sortingEnabled)
        self.mb_voca_open.setText(_translate("MainApp", "Edit File"))
        self.back.setText(_translate("MainApp", "<<"))
        self.pause.setText(_translate("MainApp", "■"))
        self.forward.setText(_translate("MainApp", ">>"))
        self.mb_show_special_case_adj.setText(_translate("MainApp", "[SPECIAL CASE]"))
        self.mb_show_dev_contact.setText(_translate("MainApp", "Contact\n"
"\n"
"Contributor"))
        self.mb_show_dev_detail.setText(_translate("MainApp", "@email\n"
"@id\n"
"@name/githubname"))
