# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resource/src/ui/updater.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(500, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(500, 500))
        Dialog.setMaximumSize(QtCore.QSize(500, 500))
        Dialog.setStyleSheet("/* Pallete --------------------------------- \n"
"\n"
"lightgray : rgb(242, 242, 247)\n"
"gray : rgb(141, 141, 147)\n"
"darkgray : rgb(122, 122, 128)\n"
"\n"
"grayorange : rgb(228, 175, 10)\n"
"pointorange : rgb(250, 188, 1)\n"
"\n"
"blue : rgb(0, 155, 255)\n"
"bluehover : rgba(0, 155, 255, 80)\n"
"\n"
"--------------------------------------- */\n"
"QObject {\n"
"font: 14px \"Noto Sans KR SemiBold\";\n"
"}\n"
"QDialog {\n"
"background-color: white;\n"
"}\n"
"#UpdaterBackground {\n"
"background-image: url(\"C:/Users/Gonyo/Documents/GitHub/VisualVocaApp/resource/src/img/UpdateImage.svg\");\n"
"}\n"
"QLabel#UpdaterState {\n"
"qproperty-alignment: \'AlignVCenter | AlignHCenter\';\n"
"}\n"
"#UpdaterBtns .QPushButton {\n"
"border-radius: 5px;\n"
"border: 0px solid;\n"
"background-color: rgb(242, 242, 247);\n"
"color: black;\n"
"}\n"
"#UpdaterBtns #UpdateSkip:hover {\n"
"background-color: rgb(122, 122, 128);\n"
"color: white;\n"
"}\n"
"#UpdaterBtns .QPushButton#UpdateDo {\n"
"background-color: rgb(250, 188, 1);\n"
"color: white;\n"
"}\n"
"#UpdaterBtns .QPushButton#UpdateDo:hover {\n"
"background-color: rgba(250, 188, 1, 80);\n"
"}")
        self.UpdaterBackground = QtWidgets.QLabel(Dialog)
        self.UpdaterBackground.setGeometry(QtCore.QRect(0, 0, 500, 500))
        self.UpdaterBackground.setMinimumSize(QtCore.QSize(500, 500))
        self.UpdaterBackground.setMaximumSize(QtCore.QSize(500, 500))
        self.UpdaterBackground.setText("")
        self.UpdaterBackground.setObjectName("UpdaterBackground")
        self.UpdaterState = QtWidgets.QLabel(Dialog)
        self.UpdaterState.setGeometry(QtCore.QRect(0, 280, 501, 31))
        self.UpdaterState.setObjectName("UpdaterState")
        self.UpdaterBtns = QtWidgets.QWidget(Dialog)
        self.UpdaterBtns.setGeometry(QtCore.QRect(100, 360, 301, 70))
        self.UpdaterBtns.setMinimumSize(QtCore.QSize(0, 70))
        self.UpdaterBtns.setMaximumSize(QtCore.QSize(16777215, 70))
        self.UpdaterBtns.setObjectName("UpdaterBtns")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.UpdaterBtns)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.UpdateSkip = QtWidgets.QPushButton(self.UpdaterBtns)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.UpdateSkip.sizePolicy().hasHeightForWidth())
        self.UpdateSkip.setSizePolicy(sizePolicy)
        self.UpdateSkip.setMinimumSize(QtCore.QSize(50, 50))
        self.UpdateSkip.setMaximumSize(QtCore.QSize(50, 50))
        self.UpdateSkip.setObjectName("UpdateSkip")
        self.horizontalLayout.addWidget(self.UpdateSkip)
        self.UpdateDo = QtWidgets.QPushButton(self.UpdaterBtns)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.UpdateDo.sizePolicy().hasHeightForWidth())
        self.UpdateDo.setSizePolicy(sizePolicy)
        self.UpdateDo.setMinimumSize(QtCore.QSize(0, 50))
        self.UpdateDo.setMaximumSize(QtCore.QSize(16777215, 50))
        self.UpdateDo.setObjectName("UpdateDo")
        self.horizontalLayout.addWidget(self.UpdateDo)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.UpdaterState.setText(_translate("Dialog", "Downloading ..."))
        self.UpdateSkip.setText(_translate("Dialog", "Skip"))
        self.UpdateDo.setText(_translate("Dialog", "Update"))
