# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/Gonyo/Documents/GitHub/VisualVocaApp/dist/resource/src/ui/updater.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(500, 550)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(500, 550))
        Dialog.setMaximumSize(QtCore.QSize(500, 550))
        Dialog.setStyleSheet("/* Pallete --------------------------------- \n"
"\n"
"lightgray : rgb(242, 242, 247)\n"
"gray : rgb(141, 141, 147)\n"
"darkgray : rgb(122, 122, 128)\n"
"\n"
"grayorange : rgb(228, 175, 10)\n"
"pointorange : rgb(250, 188, 1)\n"
"\n"
"blue : rgb(0, 155, 255)\n"
"bluehover : rgba(0, 155, 255, 80)\n"
"\n"
"--------------------------------------- */\n"
"QObject {\n"
"border: 0px solid blue;\n"
"font: 16px \"Noto Sans KR SemiBold\";\n"
"}\n"
"QDialog {\n"
"background-color: white;\n"
"}\n"
"#UpdaterBackground {\n"
"background-image: url(\"C:/Users/Gonyo/Documents/GitHub/VisualVocaApp/resource/src/img/UpdateImage.svg\");\n"
"}\n"
"QLabel#UpdaterState {\n"
"font: 12px; \n"
"qproperty-alignment: \'AlignVCenter | AlignHCenter\';\n"
"}\n"
"#UpdaterBtns .QPushButton {\n"
"border-radius: 5px;\n"
"border: 0px solid;\n"
"background-color: rgb(242, 242, 247);\n"
"color: black;\n"
"}\n"
"#UpdaterBtns #UpdateSkip:hover {\n"
"background-color: rgb(122, 122, 128);\n"
"color: white;\n"
"}\n"
"\n"
"\n"
"#UpdaterBtns .QPushButton#UpdateDo {\n"
"background-color: rgb(250, 188, 1);\n"
"color: white;\n"
"}\n"
"#UpdaterBtns .QPushButton#UpdateDo:hover {\n"
"background-color: rgba(250, 188, 1, 80);\n"
"}\n"
"\n"
"\n"
"\n"
"#UpdaterTopbar .QPushButton#close_ {\n"
"border-radius: 8px;\n"
"font: 12px;\n"
"text-align: center;\n"
"color: rgb(113, 22, 15);\n"
"background: rgb(255, 96, 92);\n"
"}\n"
"#UpdaterTopbar .QPushButton#close_:hover {\n"
"background: rgba(255, 96, 92, 150);\n"
"color: rgba(113, 22, 15, 150);\n"
"}\n"
"\n"
"\n"
"\n"
"#UpdaterTopbar .QPushButton#minimize_ {\n"
"border-radius: 8px;\n"
"font: 20px;\n"
"text-align: center;\n"
"color: rgb(143, 88, 28);\n"
"background: rgb(255, 189, 68);\n"
"}\n"
"#UpdaterTopbar .QPushButton#minimize_:hover {\n"
"color: rgba(143, 88, 28, 150);\n"
"background: rgba(255, 189, 68, 150);\n"
"}")
        self.UpdaterBackground = QtWidgets.QLabel(Dialog)
        self.UpdaterBackground.setGeometry(QtCore.QRect(0, 50, 500, 500))
        self.UpdaterBackground.setMinimumSize(QtCore.QSize(500, 500))
        self.UpdaterBackground.setMaximumSize(QtCore.QSize(500, 500))
        self.UpdaterBackground.setText("")
        self.UpdaterBackground.setObjectName("UpdaterBackground")
        self.UpdaterState = QtWidgets.QLabel(Dialog)
        self.UpdaterState.setGeometry(QtCore.QRect(0, 330, 501, 31))
        self.UpdaterState.setObjectName("UpdaterState")
        self.UpdaterBtns = QtWidgets.QWidget(Dialog)
        self.UpdaterBtns.setGeometry(QtCore.QRect(100, 410, 301, 70))
        self.UpdaterBtns.setMinimumSize(QtCore.QSize(0, 70))
        self.UpdaterBtns.setMaximumSize(QtCore.QSize(16777215, 70))
        self.UpdaterBtns.setObjectName("UpdaterBtns")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.UpdaterBtns)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.UpdateSkip = QtWidgets.QPushButton(self.UpdaterBtns)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.UpdateSkip.sizePolicy().hasHeightForWidth())
        self.UpdateSkip.setSizePolicy(sizePolicy)
        self.UpdateSkip.setMinimumSize(QtCore.QSize(50, 50))
        self.UpdateSkip.setMaximumSize(QtCore.QSize(50, 50))
        self.UpdateSkip.setObjectName("UpdateSkip")
        self.horizontalLayout.addWidget(self.UpdateSkip)
        self.UpdateDo = QtWidgets.QPushButton(self.UpdaterBtns)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.UpdateDo.sizePolicy().hasHeightForWidth())
        self.UpdateDo.setSizePolicy(sizePolicy)
        self.UpdateDo.setMinimumSize(QtCore.QSize(0, 50))
        self.UpdateDo.setMaximumSize(QtCore.QSize(16777215, 50))
        self.UpdateDo.setObjectName("UpdateDo")
        self.horizontalLayout.addWidget(self.UpdateDo)
        self.UpdaterTopbar = QtWidgets.QWidget(Dialog)
        self.UpdaterTopbar.setGeometry(QtCore.QRect(429, 0, 71, 51))
        self.UpdaterTopbar.setObjectName("UpdaterTopbar")
        self.close_ = QtWidgets.QPushButton(self.UpdaterTopbar)
        self.close_.setGeometry(QtCore.QRect(38, 15, 16, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.close_.sizePolicy().hasHeightForWidth())
        self.close_.setSizePolicy(sizePolicy)
        self.close_.setMinimumSize(QtCore.QSize(16, 16))
        self.close_.setMaximumSize(QtCore.QSize(16, 16))
        self.close_.setCheckable(True)
        self.close_.setObjectName("close_")
        self.minimize_ = QtWidgets.QPushButton(self.UpdaterTopbar)
        self.minimize_.setGeometry(QtCore.QRect(13, 15, 16, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minimize_.sizePolicy().hasHeightForWidth())
        self.minimize_.setSizePolicy(sizePolicy)
        self.minimize_.setMinimumSize(QtCore.QSize(16, 16))
        self.minimize_.setMaximumSize(QtCore.QSize(16, 16))
        self.minimize_.setCheckable(True)
        self.minimize_.setObjectName("minimize_")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.UpdaterState.setText(_translate("Dialog", "Downloading ..."))
        self.UpdateSkip.setText(_translate("Dialog", "Skip"))
        self.UpdateDo.setText(_translate("Dialog", "Update"))
        self.close_.setText(_translate("Dialog", "×"))
        self.minimize_.setText(_translate("Dialog", "-"))
